[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "luma>=2.3.20",
    "luma-oled>=3.14.0",
    "pillow>=11.3.0",
    "psutil>=7.0.0",
]
